### ISSUE TITLE
Unable to Authenticate because of login failed. -- I'm entering in correct credentials

### ISSUE THREAD

**Issue by ColtonYYZ** [AngellusMortis/sxm-docker#4]
`2024-05-06 07:30:43 7167b1ba8d0e sxm_player[8] INFO Attempting to connect SXM Client (next in 10 seconds)
2024-05-06 07:30:44 7167b1ba8d0e /usr/local/lib/python3.9/site-packages/sxm/client.py[12] ERROR Unable to authenticate because login failed
2024-05-06 07:30:47 7167b1ba8d0e /usr/local/lib/python3.9/site-packages/sxm/client.py[12] ERROR Unable to authenticate because login failed
2024-05-06 07:30:50 7167b1ba8d0e /usr/local/lib/python3.9/site-packages/sxm/client.py[12] ERROR Unable to authenticate because login failed
/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:1548: RuntimeWarning: coroutine 'BaseEventLoop.getaddrinfo' was never awaited
  result = await get_running_loop().getaddrinfo(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 149, in connect_tcp
    addr_obj = ip_address(remote_host)
  File "/usr/local/lib/python3.9/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: 'player.siriusxm.com' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/sxm_player/runner.py", line 50, in worker_wrapper
    worker = worker_class(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sxm_player/workers/server.py", line 50, in __init__
    self.sxm.authenticate()
  File "/usr/local/lib/python3.9/site-packages/sxm/client.py", line 938, in authenticate
    return make_sync(self.async_client.authenticate)()
  File "/usr/local/lib/python3.9/site-packages/make_it_sync/func_wrapper.py", line 63, in wrapped_call
    return _sync_version_of_function(fn, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/make_it_sync/func_wrapper.py", line 14, in _sync_version_of_function
    return loop.run_until_complete(r)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 86, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 48, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 51, in __call__
    result = await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sxm/client.py", line 301, in authenticate
    if not self.is_logged_in and not await self.login():
  File "/usr/local/lib/python3.9/site-packages/sxm/client.py", line 281, in login
    data = await self._post("modify/authentication", postdata, authenticate=False)
  File "/usr/local/lib/python3.9/site-packages/sxm/client.py", line 654, in _post
    return await self._request(
  File "/usr/local/lib/python3.9/site-packages/sxm/client.py", line 606, in _request
    response = await self._make_request(method, path, params, url_format=url_format)
  File "/usr/local/lib/python3.9/site-packages/sxm/client.py", line 564, in _make_request
    response = await self._session.post(url, json=params)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1807, in post
    return await self.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1481, in request
    response = await self.send(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1568, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1604, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1640, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1681, in _send_single_request
    ) = await transport.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 283, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 136, in handle_async_request
    self.socket = await self._open_socket(timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 163, in _open_socket
    return await self._backend.open_tcp_stream(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/auto.py", line 44, in open_tcp_stream
    return await self.backend.open_tcp_stream(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 150, in open_tcp_stream
    stream = await anyio.connect_tcp(
  File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 152, in connect_tcp
    gai_res = await getaddrinfo(target_host, remote_port, family=family,
  File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 416, in getaddrinfo
    gai_res = await get_asynclib().getaddrinfo(encoded_host, port, family=family, type=type,
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1548, in getaddrinfo
    result = await get_running_loop().getaddrinfo(
  File "/usr/local/lib/python3.9/site-packages/sxm_player/signals.py", line 29, in default_signal_handler
    raise exception_class()
sxm_player.signals.TerminateInterrupt
2024-05-06 07:30:53 7167b1ba8d0e sxm_player[8] INFO Terminated sxm after 3 attempt(s)
2024-05-06 07:30:53 7167b1ba8d0e sxm_player[8] ERROR Exception: Process sxm failed to startup after 10.0 seconds
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sxm_player/cli.py", line 123, in main
    event_loop(**locals())
  File "/usr/local/lib/python3.9/site-packages/sxm_player/cli.py", line 155, in event_loop
    spawn_sxm_worker(runner, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sxm_player/cli.py", line 139, in spawn_sxm_worker
    runner.create_worker(
  File "/usr/local/lib/python3.9/site-packages/sxm_player/runner.py", line 274, in create_worker
    worker = Worker(
  File "/usr/local/lib/python3.9/site-packages/sxm_player/runner.py", line 117, in __init__
    raise RuntimeError(
RuntimeError: Process sxm failed to startup after 10.0 seconds
Traceback (most recent call last):
  File "/usr/local/bin/sxm-player", line 8, in <module>
    sys.exit(start())
  File "/usr/local/lib/python3.9/site-packages/sxm_player/__main__.py", line 13, in start
    app()
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/sxm_player/cli.py", line 123, in main
    event_loop(**locals())
  File "/usr/local/lib/python3.9/site-packages/sxm_player/cli.py", line 155, in event_loop
    spawn_sxm_worker(runner, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sxm_player/cli.py", line 139, in spawn_sxm_worker
    runner.create_worker(
  File "/usr/local/lib/python3.9/site-packages/sxm_player/runner.py", line 274, in create_worker
    worker = Worker(
  File "/usr/local/lib/python3.9/site-packages/sxm_player/runner.py", line 117, in __init__
    raise RuntimeError(
RuntimeError: Process sxm failed to startup after 10.0 seconds`

**Comment by geolaw** [comment]
check your password. if you have any kind of special characters, you may need to enclose the password with single quotes
    -e SXM_PASSWORD='myPa$$word!'
